version: '3.9'

services:
  db:
    image: postgres:15
    container_name: mini_app_db
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: mini_app_1712
      POSTGRES_DB: mini_app_db
    ports:
      - "5432:5432"
    restart: always

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: django_forum
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project_forum.settings
      - DATABASE_URL=postgres://ivan:mini_app_1712@db:5432/mini_app_db
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 project_forum.wsgi:application"
